variable "common_key" {}
variable "region" {}
variable "short_env" {}
variable "environment" {}
variable "instance_type" {}
variable "service_name" {}
variable "public_sub" {}
variable "local_ips" {}
variable "service_vpc" {}
