variable "common_key" {}
variable "region" {}
variable "short_env" {}
variable "environment" {}
variable "instance_type" {}
variable "service_name" {}
variable "public_subs" {}
variable "developers_site" {}
variable "service_vpc" {}
variable "db_sg" {}
